[package]
name = "polkadot-cli"
version = "0.1.0"
authors = ["Luke Schoen <ltfschoen@gmail.com>"]

[dependencies]
clap = { version = "2.31.2", features = ["yaml", "debug"] } # https://clap.rs/
env_logger = "0.5.8"
log = "0.4.1"